---
- name: Install ZFS
  ansible.builtin.include_tasks: install.yml
- name: Configure Zpools
  ansible.builtin.include_tasks: pools.yml
- name: "Setup ZFS datasets: filesystems, snapshots, volumes"
  ansible.builtin.include_tasks: datasets.yml
