---
- name: Skip Archlinux installation
  ansible.builtin.meta: end_play
  when: ansible_facts['os_family'] != 'Archlinux'

- name: Archlinux base setup
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - pacman.yml
    - locales.yml
    - yay.yml
    - paru.yml
