---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart ntfy
  ansible.builtin.systemd:
    name: ntfy
    state: restarted
    daemon_reload: true

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
