---
# NTP configuration file
ntp_config_file: "/etc/ntp.conf"

# NTP servers to use.
ntp_pools: -" 0.uk.pool.ntp.org" -" 1.uk.pool.ntp.org" -" 2.uk.pool.ntp.org" -" 3.uk.pool.ntp.org"

# System timezone
ntp_timezone: "Europe/London"

# NTP drift file location
# (keeps track of your clock's time deviation)
ntp_drift_file: "/var/lib/ntp/ntp.drift"

# NTP security restrictions
ntp_restrict: "kod nomodify notrap nopeer noquery limited"

# Networks allowed to query this ntpd server
ntp_allowed_networks:
  - "127.0.0.1"
  - "::1"
# - "192.168.1.0 mask 255.255.255.0"

ntp_port: 123
