---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Install zsh plugins
  ansible.builtin.include_tasks: plugins.yml
- name: Setup zsh for the user(s)
  ansible.builtin.include_tasks: user-setup.yml
  vars:
    zsh_user: "{{ item }}"
  loop: "{{ zsh_users | default([]) }}"
