---
- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: "{{ postgres_service_name }}"
    state: restarted

- name: Reload PostgreSQL
  ansible.builtin.systemd:
    name: "{{ postgres_service_name }}"
    state: reloaded
