---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload systemd user
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: false
  become_user: "{{ ansible_user }}"

- name: Restart Immich
  ansible.builtin.systemd:
    name: immich.service
    state: restarted
    scope: user
  become: false
  become_user: "{{ ansible_user }}"

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
