---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload systemd user
  ansible.builtin.command: "systemctl --user daemon-reload"
  become: true
  become_user: "{{ ansible_user }}"

- name: Restart Immich
  ansible.builtin.command: "systemctl --user restart immich.service"
  become: true
  become_user: "{{ ansible_user }}"

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
