---
- name: Install usbutils
  package:
    name: usbutils
    state: present
  changed_when: false

- name: Install htop
  package:
    name: htop
    state: present
  changed_when: false

- name: Install bottom
  package:
    name: bottom
    state: present
  changed_when: false

- name: Install wget
  package:
    name: wget
    state: present
  changed_when: false

- name: Install dig utility
  package:
    name: "{{ (ansible_facts['os_family'] == 'Archlinux') | ternary('bind', 'dnsutils') }}"
    state: present
  changed_when: false
