---
- name: Ensure disks are formatted correctly
  ansible.builtin.include_tasks: partitioning.yml
  loop: "{{ disk_partitioning | default([]) }}"

- name: Enable trim SSD if there is at least one
  ansible.builtin.include_tasks: trim-ssd.yml
