---
- name: "Reload systemd and restart nfs-server"
  ansible.builtin.systemd:
    name: "nfsv4-server"
    state: restarted
    daemon_reload: true

- name: "Update exportfs"
  ansible.builtin.command: exportfs -ra
